default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>

development:
  <<: *default
  database: garden_planner_development

test:
  <<: *default
  database: garden_planner_test

production:
  <<: *default
  database: garden_planner_production
  username: garden_planner
  password: <%= ENV["DATABASE_PASSWORD"] %>
